#!/usr/bin/env python
# -*- coding: utf-8 -*-
import sys
import syslog
import argparse
from netcop.configurador import configurador

# Manejo de parametros
# -----------------------------------------------------------------------
parser = argparse.ArgumentParser(usage='''
Permite leer y establecer la configuracion del sistema operativo y netcop.
''')
parser.add_argument("-s", "--set",
                    help="Aplica configuracion detallada en %s" %
                          configurador.TMP_CONFIG_FILE,
                    action="store_true")
args = parser.parse_args()

try:
    # Aplica cambios detallados en el arhivo temporal
    # -----------------------------------------------------------------------
    if args.set:
        if configurador.existe_archivo_temporal():
            syslog.syslog(syslog.LOG_DEBUG,
                "[*] Se encontro archivo temporal")
            syslog.syslog(syslog.LOG_DEBUG,
                "[*] Iniciando configuracion")
            configurador.configurar()
            syslog.syslog(syslog.LOG_DEBUG,
                "[*] Aplicando cambios")
            configurador.aplicar_cambios()
            syslog.syslog(syslog.LOG_DEBUG,
                "[*] Borrando archivo temporal")
            configurador.borrar_temporal()
            syslog.syslog(syslog.LOG_INFO,
                "[*] Configuracion realizada con exito")

    # Lee cambios desde archivos de sistema operativo
    # -----------------------------------------------------------------------
    else:
        parametros = configurador.obtener_config()
        print("\n".join("{k}={v}" for k, v in parametros))

except Exception as e:
    syslog.syslog(syslog.LOG_CRIT, str(e))
    print >> sys.stderr, str(e)
    sys.exit(1)
