#!/usr/bin/env python
# -*- coding: utf-8 -*-
import sys
import syslog
from netcop.configurador import configurador

try:
    if configurador.existe_archivo_temporal():
        syslog.syslog(syslog.LOG_DEBUG, "Existe archivo temporal")
        configurador.configurar()
        configurador.aplicar_cambios()
        configurador.borrar_temporal()
        syslog.syslog(syslog.LOG_INFO, "Configuracion realizada con exito")
except Exception as e:
    syslog.syslog(syslog.LOG_CRIT, e.message)
    sys.exit(1)
